#!/bin/sh

read -r -d '' brew_taps << TAPS
jenv/jenv
TAPS

read -r -d '' brew_packages << BREW
autoenv
bash-completion
brew-cask
git
gradle
leiningen
maven
scala
tomcat
tree
vim
jenv
BREW

read -r -d '' cask_packages << CASK
calibre
dropbox
google-chrome
intellij-idea
iterm2
kindle
macvim
skype
spotify
sublime-text
utorrent
vagrant
virtualbox
vlc
CASK

function install_packages() {
	local type="$1"
	local packages_to_install="$2"
	local check_command=
	local install_command=
	
	if [[ "$type" == "tap" ]]; then
		check_command="brew tap"
		install_command="brew tap"
	elif [[ "$type" == "brew" ]]; then
		check_command="brew list"
		install_command="brew install"
	elif [[ "$type" == "cask" ]]; then
		check_command="brew cask list"
		install_command="brew cask install"
	else
		echo "can only install 'brew' or 'cask' packages"
		exit 1
	fi
	
	for package in $packages_to_install; do
		if [[ `$check_command` == *$package* ]]; then
			echo "$package already installed"
		else
			echo "installing $package"
			`$install_command $package`
		fi
	done
}

echo
echo "######################"
echo "Updating brew packages"
echo "######################"
brew update

echo
echo "####################"
echo "Installing brew taps"
echo "####################"
install_packages "tap" "$brew_taps"

echo
echo "########################"
echo "Installing brew packages"
echo "########################"
install_packages "brew" "$brew_packages"

echo
echo "########################"
echo "Installing cask packages"
echo "########################"
install_packages "cask" "$cask_packages"
