#!/bin/sh

dotfiles="bash_profile bashrc vimrc bash_aliases gitconfig zshrc zsh_aliases"
backup_dir=~/.dotfiles.bak/$(date +"%m-%d-%y_%H-%M-%S")

echo
echo "#######################"
echo "# Installing dotfiles #"
echo "#######################"

echo "Creating backup directory in $backup_dir"
mkdir -p $backup_dir

for file in $dotfiles; do
  echo "Installing dotfile $file"
  mv ~/".$file" $backup_dir
  ln -s ~/dev/dotfiles/$file ~/".$file"
done
