#!/bin/sh
echo "Updating homebrew"
brew update

if [ "$(brew list | grep ansible)" == "" ]; then
  brew install ansible
fi

# run ansible
ansible-playbook -i hosts site.yml -c local

if [[ ! -d ~/.vim/bundle/vundle ]]; then
  echo
  echo "#####################"
  echo "# Installing vundle #"
  echo "#####################"
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
fi

if [[ ! -d ~/.oh-my-zsh ]]; then
  echo
  echo "########################"
  echo "# Installing oh-my-zsh #"
  echo "########################"
	curl -L github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh
fi

