#! /bin/sh

declare -a TAPS=()
declare -a BREWS=()
declare -a CASKS=()
declare -a DOTFILES=()

# load config from disk. this allows us to update these files for example when the
# user installs a new brew, automatically with aliases
while IFS='' read -r line || [[ -n "$line" ]]; do TAPS+=($line); done < ".taps"
while IFS='' read -r line || [[ -n "$line" ]]; do BREWS+=($line); done < ".brews"
while IFS='' read -r line || [[ -n "$line" ]]; do CASKS+=($line); done < ".brews"
while IFS='' read -r line || [[ -n "$line" ]]; do DOTFILES+=($line); done < ".dotfiles"

function install_apps {
  which -s brew
  if [[ $? != 0 ]] ; then
    echo 'installing brew...'
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    echo 'updating brew...'
    brew update
  fi

  echo 'installing taps...'
  installed_taps=$(brew tap-info --installed)
  for tap in ${TAPS[@]}; do
    if [[ ${installed_taps} != *"$tap"* ]]; then
      echo " - ${tap}"
      brew tap ${tap}
    fi
  done

  echo 'installing brews...'
  installed_brews=$(brew list)
  for brew in ${BREWS[@]}; do
    if [[ ${installed_brews} != *"$brew"* ]]; then
      echo " - ${brew}"
      brew install $brew
    fi
  done

  echo 'installing casks...'
  installed_casks=$(brew cask list)
  for cask in ${CASKS[@]}; do
    if [[ ${installed_casks} != *"$cask"* ]]; then
      echo " - ${cask}"
      brew cask install $cask
    fi
  done
}

function symlink_dotfiles {
  echo 'creating symlinks for dotfiles'
  for dotfile in ${DOTFILES[@]}; do
    echo " - ${dotfile}"
    ln -sf "${PWD}/${dotfile}" "${HOME}/${dotfile}"
  done
}

function install {
  install_apps
  symlink_dotfiles
}

install
