#!/bin/sh

declare -a DOTFILES=(
.bash_profile
.bashrc
.editorconfig
.npmrc
.tern-project
.tmux.conf
.vimrc
.zshrc
)

function symlink_dotfiles {
  echo 'creating symlinks for dotfiles'
  for dotfile in ${DOTFILES[@]}; do
    echo " - ${dotfile}"
    ln -sf "${PWD}/${dotfile}" "${HOME}/${dotfile}"
  done
}

function install {
  symlink_dotfiles
}

install

