---
- name: check is brew installed
  stat: path=/usr/local/bin/brew
  register: brew_installed

- name: install homebrew if not already installed
  shell: ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
  when: not brew_installed.stat.exists