---
- name: install brew taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - jenv/jenv

- name: install brew packages
  homebrew: name={{ item }} state=present
  with_items: 
    - autoenv
    - bash-completion
    - brew-cask
    - git
    - gradle
    - jenv
    - leiningen
    - maven
    - play
    - sbt
    - scala
    - tomcat
    - tree
    - vim
