font_size 14.0

font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_shape block

scrollback_lines 10000

detect_urls yes

copy_on_select clipboard

enable_audio_bell no

remember_window_size yes

include ./tokyo-night-kitty.conf
