[package]
disabled = true

[kubernetes]
symbol = "☸  "
style = "bold blue"
disabled = false
[kubernetes.context_aliases]
"prod-us-a" = "prod"
"qa-eu-a" = "qa"

[aws]
disabled=true

[cmd_duration]
disabled=true

[java]
style="red"