---
- name: install brew cask packages
  homebrew_cask: name={{ item }} state=present
  with_items:
    - atom
    - calibre
    - dropbox
    - google-chrome
    - intellij-idea
    - iterm2
    - kindle
    - knock
    - macvim
    - skype
    - spotify
    - sublime-text
    - transmission
    - utorrent
    - vagrant
    - virtualbox
    - vlc
